version: "3.7"

services:
  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - ./app:/home/app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
    ports:
      - "3307:3306"

  nginx:
    build: ./docker/nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./app:/home/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

#  certbot:
#    image: certbot/certbot
#    restart: unless-stopped
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot