version: "3.8"

services:
  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - ./app:/home/app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"

  nginx:
    build: ./docker/nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./app:/home/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

