version: "3.8"

services:
  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - ./app:/home/app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
    ports:
      - "${DB_PORT}:3306"

  nginx:
    build: ./docker/nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./app:/home/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

#  certbot:
#    image: certbot/certbot
#    restart: unless-stopped
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
